### ISSUE TITLE
`Unable to speak entry!` error for this application on Ubuntu

### ISSUE THREAD

**Issue by eleehiga** [aaronhktan/jyut-dict#131]
**Describe the bug**

**To Reproduce**
1. Go to the `Jyut Dictionary` application
2.  Search up a word
3. Click on the microphone icon for the word's definition
4. Click `Add Voice` when the `Unable to speak entry!` error appears
6. See error in the second picture which shows the Debian page and the heading `Error`

**Expected behavior**
Able to add Chinese mainland and Hong Kong voices

**Screenshots**
![image](https://user-images.githubusercontent.com/55113159/236685509-b9d8b8f2-c15b-42cd-905e-b8bbcd39fc98.png)

![Snapshot_2023-05-07_08-04-11](https://user-images.githubusercontent.com/55113159/236685606-138032f4-ed79-4270-a17e-5a49d0b31785.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Budgie
 - Version 22.10

**Comment by aaronhktan** [comment]
One piece of information to better diagnose:
- What version of the Linux application are you using? (AppImage or Debian package?)

Speech isn't supported in the AppImage version, because I could never figure out how to get `linuxdeployqt` to recognize `libspeechd-dev` as a dependency. If you're using the Debian package, you should be able to install libspeechd by doing `sudo apt install libspeechd-dev`.

Be warned that the text-to-speech synthesis on Linux is garbage though. I don't think it has pronunciation for Mandarin, and the Cantonese voice is very very robotic. 😬 

Let me know if this helps!

**Comment by eleehiga** [comment]
I am using the AppImage version, and thank you I will hopefully try what you recommended soon with the Debian version

**Comment by aaronhktan** [comment]
Since there hasn't been activity on this issue for a few days, I'll close it for now. Feel free to reopen if there's any more you need help with!

**Comment by mmwelt** [comment]
I also had this problem with the AppImage vesion.  Perhaps it would be useful to add a note somewhere to state that speech isn't currently supported when using the AppImage version, and what steps need to be taken to get speech working when using the Debian package.
