### ISSUE TITLE
Cannot type Chinese with fcitx

### ISSUE THREAD

**Issue by colibris79** [aaronhktan/jyut-dict#140]
**Describe the bug**
I am using Jyut in my Mint 21 (Ubuntu 22.04) machine with latest Appimage v2.23.0408. My input method for Chinese is fcitx which works fine with any other app in my system. But when I try to type Chinese in the search box  I just can't activate fcitx, like it does not recognize the search box.  I can paste Chinese characters from any other app though

**To Reproduce**
1. Try to write in the search box using fcitx 

**Expected behavior**
Fcitx should work with Jyut so I could type Chinese in the search box

**Desktop (please complete the following information):**
Mint 21.2 

EDIT: I've tried the previous release, v1.22.0207, both AppImage and .deb packages in an older Mint 19.3 (Ubuntu 18.04) and it has the same problem. Also tried all the previous AppImage files

And thanks for this amazing program.

**Comment by aaronhktan** [comment]
Few things to try:
- Have you installed fcitx5 and fctitx-qt5 packages? (I think this might solve it for the .deb package in Mint 19.3 but not the AppImage, since AppImage will load Qt plugins from its own directories.)
- Can you describe how you set up fcitx or have a link with a guide? I haven't set fcitx up with my machine, so being able to replicate your environment would be very helpful.
- If that doesn't work, and you're willing to spend some time, what happens if you compile from source and try to input text with fcitx? Does that work?

**Comment by colibris79** [comment]
@aaronhktan thank you so much for your answer. I'm still using the previous fctix install, so this weekend I'll give a try with fcitx5 and report back.

**Comment by aaronhktan** [comment]
Awesome, let me know how it goes. Appreciate the bug report!

**Comment by aaronhktan** [comment]
Update, did some investigation on my own and I think I've figured out the problem. I'll put the fix in the next version.

For my own notes:
- Using fcitx5 in QLineEdits in Qt requires `libfcitxplatforminputcontextplugin.so` to be in $QT_DIR/plugins/platforminputcontexts
- Building that plugin requires cloning from https://github.com/fcitx/fcitx5-qt and checking out rev `02bbbf6` since it's the last one before the CMakeLists went Qt6 only.
- Then install `extra-cmake-modules`, `gettext`,  `libfcitx5utils-dev`, `libxkbcommon-x11-dev`, and run `cmake -DCMAKE_PREFIX_PATH=$QT_DIR/gcc_64 -DENABLE_QT4=0 .`
- Finally, `cd qt5/platforminputcontext` and `make`.

**Comment by aaronhktan** [comment]
I'll close this issue for now, but I'll reply back once the next version is out and see if what I suspect is the fix actually works.

**Comment by colibris79** [comment]
Thanks. I've managed to make it work in the Mint 19.3 with Ibus (cannot install fcitx5 here).
Also in the Mint 21.2 Pc, right now I don't want to mess up too much with fcitx since everything else is working fine. I've also tried installing the deb file but it requires qt-5.15.2. Do you plan to have a ppa also for jammy (Ubuntu 22.04)?
