### ISSUE TITLE
Search all romanizations, fuzzy search

### ISSUE THREAD

**Issue by sp96296** [aaronhktan/jyut-dict#41]
Might be helpful to be able to search all romanizations (pinyin, jyutping, etc) to find characters / words so you don't have to switch between them. Perhaps a default "auto" setting, akin to how Pleco works.

Additionally, [fuzzy character/romanization recognition](https://en.wikipedia.org/wiki/Pinyin_input_method) e.g. l <-> n (lei <-> nei).

Example of some fuzzy pinyin rules in Windows: 
![image](https://user-images.githubusercontent.com/36968514/123700389-69cbef00-d82e-11eb-8b0e-8279af4f86c1.png)

**Comment by aaronhktan** [comment]
Hmm, I'm actually not a fan of Pleco's auto-switching — I find it very annoying, personally. I will not be implementing a way to search all romanizations.

The fuzzy romanization idea is very interesting (and super useful for the n-l merging and ng-null initial sound changes). I wanted to do something like that, but haven't been able to figure out a way of doing it cleanly without having a bunch of weird edge cases in the search code. Because of that, I'm going to close this issue for now, but might reopen it if I can find the time to look more closely at it.

**Comment by aaronhktan** [comment]
I've now implemented a basic auto-switching feature! I still haven't had the bandwidth to do fuzzy searching at the moment though.
