### ISSUE TITLE
Revise words.hk parsing script

### ISSUE THREAD

**Issue by aaronhktan** [aaronhktan/jyut-dict#42]
In the discussion of Issue #29, it was brought to my attention that words.hk provides a downloadable, parseable file of all the entries in the dictionary at [this link](https://words.hk/static/all.csv.gz) (Thanks, @hnfong!).

The old implementation scrapes all the webpages and then parses each of the downloaded files; this is brittle (prone to breaking if the structure of the webpage changes, as it has twice since mid-2020 when the initial scrape was done), and might not be the best for words.hk's servers.

This new implementation should download the provided file from that link, and then parse the downloaded file into the Jyut Dictionary database format.

**Comment by AlienKevin** [comment]
**I finally managed to add support for inline # links!** The words.hk format looks simple at first sight but has many exceptions. One of the most annoying exceptions is the multiline explanations like the ones in entry 天干地支. They are extremely rare but nevertheless do show up. Also, words.hk syntax for inline # links is not very bulletproof, because they actually allow punctuations in entry names like "A.math". So you might theoretically see links embedded in an English explanation like this: "See #A.math." You can't be certain which period '.' should be the word boundary here. Luckily, entries like A.math are extremely rare and I haven't seen people linking to such entries.

And since words.hk doesn't have an editor preview nor syntax checker on their dictionary page, contributors sometimes make syntax mistakes. I detected about ten mistakes just by running my parser through the CSV file. I have fixed all of them through the website, so now the parser should be able to parse everything correctly (at least the things in my test cases).

I'll add a README and some documentation for the parser soon.

**Comment by aaronhktan** [comment]
Nice! That's some solid progress. I think I saw some discussion in editor groups for adding non-standard Jyutping to entries (e.g. 'sgen1' for the entry 'scan') - is that something your crate deals with at all, or do you take whatever string is in that field with no other processing?

**Comment by AlienKevin** [comment]
My crate currently parses everything between the '(' and ')' after the sentence as a jyutping clause. I haven't attempted to parse the individual pronunciations because the syntax they have is quite wild... You can have '!' for incompatible sounds or as a fill-in-the-blank sort of thing. I did take a look at their Django backend code. They seem to handle some edge cases like the '!' I mentioned above. I'm gonna look into it further.

**Comment by AlienKevin** [comment]
**I managed to export words.hk to Apple Dictionary!** The layout is quite similar to the website's though I need to tinker with the spacing more. I also finished all the docs and README and they are all on https://github.com/AlienKevin/wordshk-tools. With regard to the Jyutping parsing, I haven't implemented it in my parser because I see benefits in both the [ruby](https://en.m.wikipedia.org/wiki/Ruby_character) approach (words.hk does this) and having a standalone Jyutping sentence underneath the Chinese characters (jyut-dict does this). It is hard to decide on which one to pick plus I'm kinda lazy. So I chose the standalone approach for now.

<img width="1093" alt="截圖 2021-11-19 下午11 11 46" src="https://user-images.githubusercontent.com/22850071/142731734-bc9f094e-fe89-4ffa-8a32-8d6368d7ab6a.png">

<br/>

<img width="1095" alt="apple_dict_screenshot" src="https://user-images.githubusercontent.com/22850071/142731728-7f5b7120-9b83-4f40-bae1-f25dc77480f0.png">

<br/>

![截圖 2021-11-20 上午10 28 46](https://user-images.githubusercontent.com/22850071/142731992-22212a41-dcec-4de3-b883-48afa2baba34.png)

**Comment by AlienKevin** [comment]
> Nice! That's some solid progress. I think I saw some discussion in editor groups for adding non-standard Jyutping to entries (e.g. 'sgen1' for the entry 'scan') - is that something your crate deals with at all, or do you take whatever string is in that field with no other processing?

I finally managed to match the Jyutping with the words! I used a variant of the [Longest Common Subsequence](https://eecs376.github.io/notes/algorithms.html#longest-common-subsequence) algorithm, which you can see in this [commit](https://github.com/AlienKevin/wordshk-tools/commit/5a6a6639510772fd20466862dc5265bd6fe149d9). My (hopefully) finalized port of words.hk to Apple Dictionary looks like below:

![截圖 2021-12-03 上午11 33 29](https://user-images.githubusercontent.com/22850071/144667387-52593d48-d94c-4dc2-9f44-da2c461c65e8.png)

**Comment by AlienKevin** [comment]
@aaronhktan Happy holidays! How are you doing? I published my rust library as `wordshk_tools` to [crates.io](https://crates.io/crates/wordshk_tools). Feel free to use any of the functions in the library for parsing. Complete docs for each function are on [docs.rs](https://docs.rs/wordshk_tools/latest/wordshk_tools/). I'm not familiar with Qt but it seems that your library uses C++ and python. Rust offers C bindings and dylib generation that can be called in both C++ and python, so it might work with your library.

Here are some functions that might be useful:
* [parse_dict](https://docs.rs/wordshk_tools/latest/wordshk_tools/fn.parse_dict.html): Parse the entire CSV source file into a struct called Dict.
Quirks: need to manually remove the first line of metadata generated by the server during download
* [parse_jyutping](https://docs.rs/wordshk_tools/latest/wordshk_tools/fn.parse_jyutping.html): Parse a Jyutping (customized for words.hk)
Quirks: do not handle weird edge cases with '!', or currently invalid jyutping forms like "!sdet3" that begins with a '!'

**Comment by aaronhktan** [comment]
Happy holidays!

That's great! I don't have much experience with Rust, but I'll check it out. Seems like really good work, thank you for doing this!
