### ISSUE TITLE
Add HSK 3.0 tags

### ISSUE THREAD

**Issue by shawkynasr** [aaronhktan/jyut-dict#43]
You can add [HSK 3.0 data](https://github.com/shawkynasr/HSK-official-Query-System)

**Comment by aaronhktan** [comment]
Yeah, I was considering this, especially since the Unihan data has tags for HSK level (although I think those were HSK 2.0 and not the new ones that just released this year).

One thing that's stopping me is that the SQLite database is currently set up to generate an searchable index for all "definitions", which would probably be where I put the HSK data – but that means that if somebody searches "3", every single HSK 3 character/phrase would be a result. I'll have to give the data model a bit more thought before I can make progress on this issue.

**Comment by shawkynasr** [comment]
Great Job!
Yes, CCEDICT already translated all of new words for HSK 3.0, but still no tags.
