### ISSUE TITLE
x64 Windows Installer defaults to Program Files (x86) directory for install

### ISSUE THREAD

**Issue by LawranceFung** [aaronhktan/jyut-dict#58]
This is despite the installed executable being x64.  I checked by trying to open an x64 and x86 IME in it.

**Comment by aaronhktan** [comment]
Hm! That's weird, but should be an easy fix.

https://github.com/aaronhktan/jyut-dict/blob/8d9eb4dc2df357c20dc09783ba2aeadbdbbcd133/src/jyut-dict/platform/windows/installer/config/config.xml should have the file to change, and @ApplicationsDir@ should be changed to @ApplicationsDirX64@.

**Comment by LawranceFung** [comment]
Are the instructions to build the dictionary database up-to-date?  I couldn't find set-script.py or script-individual.py

**Comment by aaronhktan** [comment]
Ah, looks like I renamed them a while back. It's now called `parse-individual.py` and `parse-set.py`.

**Comment by LawranceFung** [comment]
pip install database isn't working.  is it supposed to be database**s**?

**Comment by aaronhktan** [comment]
You shouldn't need to install `database` or `databases` — all the requirements should be specified in the `requirements.txt` file...

Are you running the script while the current working directory is `src/dictionaries`, using the command `python3 -m cedict.parse <other stuff>`?

Because of how Python's module system works, it's sensitive to where the `python3` command is invoked from and won't find the `database.py` and `objects.py` files under `src/dictionaries/database` unless you call Python from `src/dictionary`.
